#!bin/sh
# Liftover script
# for chromosomes that DO have maps to alt chromosomes, do this:
# https://martha-labbook.netlify.app/posts/converting-snp-array-data/, which references:
# https://github.com/sritchie73/liftOverPlink#usage
# https://github.com/sritchie73/liftOverPlink#addtional-tools
# usage:
# qsub -cwd -l h_vmem=10G,mem_free=10G -t 1 run_liftover_special.sh

module load python/2.7.9

# Create a lifted map file
python /users/vpillala/bin/liftover/liftOverPlink.py \
--map ukb_chr${SGE_TASK_ID}.map \
--out ukb_chr${SGE_TASK_ID}.hg38_lift \
--chain /users/vpillala/bin/liftover/hg19ToHg38.over.chain.gz

# Remove “bad” lifted SNPs from new .map file --> "good" map file
python /users/vpillala/bin/liftover/rmBadLifts.py \
--map ukb_chr${SGE_TASK_ID}.hg38_lift.map \
--out good_ukb_chr${SGE_TASK_ID}.hg38_lift.map \
--log bad_ukb_chr${SGE_TASK_ID}.hg38_lift.dat

# Create a file that contains “unlifted” and “bad” SNPs
cut -f 2 bad_ukb_chr${SGE_TASK_ID}.hg38_lift.dat > to_exclude.chr${SGE_TASK_ID}.dat
cut -f 4 ukb_chr${SGE_TASK_ID}.hg38_lift.bed.unlifted | sed "/^#/d" >> to_exclude.chr${SGE_TASK_ID}.dat 

# Generate a .ped file that excludes the “unlifted” and “bad” SNPs. --> "good" ped file
# Note: this will clobber the ukb_chr${SGE_TASK_ID}.hg38_lift MAP file generated by `liftOverPlink`:
/users/vpillala/bin/plink_linux_x86_64_20201019/plink \
--file ukb_chr${SGE_TASK_ID} \
--recode \
--out ukb_chr${SGE_TASK_ID}.hg38_lift_goodPed \
--exclude to_exclude.chr${SGE_TASK_ID}.dat

# Combine the “good” .ped and .map files
/users/vpillala/bin/plink_linux_x86_64_20201019/plink \
--ped ukb_chr${SGE_TASK_ID}.hg38_lift_goodPed.ped \
--map good_ukb_chr${SGE_TASK_ID}.hg38_lift.map \
--recode \
--out ukb_chr${SGE_TASK_ID}.hg38_lift_combined

# Convert ped/map to plink
/users/vpillala/bin/plink_linux_x86_64_20201019/plink \
--file ukb_chr${SGE_TASK_ID}.hg38_lift_combined \
--make-bed \
--out /dcl01/arking/data/static/UKBiobank/GWAS_data/plink/hg38_lift/ukb_chr${SGE_TASK_ID}.hg38_lift